project:
  type: book
  output-dir: "."

book:
  title: "Análise Exploratória de Dados"
  date: today
  chapters:
    - index.qmd
    - capitulo1.qmd
    - capitulo2.qmd
    - capitulo3.qmd
    - capitulo4.qmd

  sidebar:
    style: floating    
    background: "#F8F9FA"  
    search: true       
    collapse-level: 1  
    toc-links: true    
    logo: "logo_ufrrj.jpg"   

  page-navigation: true

render:
  by: chapter

format:
  html:
    theme:
      light: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true
    number-sections: false
    fig-cap-location: bottom
    anchor-sections: true

  pdf:
    documentclass: book

  epub: default