project:
  type: book
  output-dir: "."

book:
  title: "Análise Exploratória de Dados"
  date: today
  chapters:
    - index.qmd
    - 01-introducao.qmd
    - 02-metodologia.qmd
    - 03-resultados.qmd
    - 04-conclusao.qmd

  sidebar:
    style: floating    
    background: "#F8F9FA"  
    search: true       
    collapse-level: 1  
    toc-links: true    
    logo: "figura.png"   

  page-navigation: true

render:
  by: chapter

format:
  html:
    theme:
      light: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true
    number-sections: true
    fig-cap-location: bottom
    anchor-sections: true

  pdf:
    documentclass: book

  epub: default