project:
  type: book
  output-dir: _book
  
book:
  title: "Análise Exploratória de Dados"
  date: today
  chapters:
    - index.qmd
    - 01-introducao.qmd
    - 02-metodologia.qmd
    - 03-resultados.qmd

  sidebar:
    style: "floating"
    search: true
    collapse-level: 1

  page-navigation: true

format:
  html:
    theme:
      light: cosmo  # ou flatly, journal, etc.
    code-copy: true
    code-overflow: wrap
    toc: true
    number-sections: true
    fig-cap-location: bottom
    anchor-sections: true

  pdf:
    documentclass: book

  epub: default